"""Data model package for ebookgen."""

from models.database import (
    cancel_job,
    claim_job_by_id,
    claim_next_pending_job,
    create_book,
    create_job,
    delete_book,
    fetch_pending_jobs,
    find_latest_failed_book_by_source,
    get_book,
    get_job,
    get_latest_job_for_book,
    init_db,
    list_books,
    mark_job_done,
    mark_job_failed,
    mark_job_running,
    update_book_settings,
    update_book_status,
)
from models.schemas import Book, Job

__all__ = [
    "Book",
    "Job",
    "init_db",
    "create_book",
    "get_book",
    "delete_book",
    "list_books",
    "update_book_settings",
    "update_book_status",
    "create_job",
    "get_job",
    "get_latest_job_for_book",
    "fetch_pending_jobs",
    "claim_next_pending_job",
    "claim_job_by_id",
    "mark_job_running",
    "mark_job_done",
    "mark_job_failed",
    "cancel_job",
    "find_latest_failed_book_by_source",
]
